### PR TITLE
Load Test against Multitenant ACA-Py

### PR DESCRIPTION
**Pull request by usingtechnology**
We are adding support to run a locust load test (connect to the mediator, connect agents to agents, ping through mediator ) using a multi-tenanted ACA-Py instance.

Leveraging ELK Stack and Playground from Aries Cloudagent Python demos. We can then use the aggregated logs from the mediator and the multi-tenant ACA-Py to see total round trip of messages at the server level.

### CODE REVIEW

**Review by jleach — APPROVED** [review]

**Comment by jleach** [comment]
@usingtechnology A little beyond my expertise but LGTM. I'll leave it to you to merge when ready.

**Comment by usingtechnology** [comment]
A touch out of date, will update image and link to ELK demo.

**Comment by usingtechnology** [comment]
Updated the documentation and ACA-Py image; this PR is ready to merge. I need an approved review before I can merge.

**Review by swcurran — APPROVED** [review]
Nice!

**Pull request merged**
