### PR TITLE
feat: initial work on an AFJ mediator

### PR DESCRIPTION
**Pull request by jleach**
Initial work on creating a containerized AFJ mediator and supporting Kubernets deplouyment manifests.

### CODE REVIEW

**Review by esune — COMMENTED** [review]
I won't count as actual approver since I am not a manitainer, so I'll just leave a comment 🙂 
Looks good overall, nothing significant to report. A couple of items I'd like to ask about though:
- should the `dist` folder gitignored?
- any specific reason to use `gulp` vs `tsc` to compile to `js` code?
- any advantage of using `yarn` over plain-old `npm`?

**Review by swcurran — APPROVED** [review]

**Comment by swcurran** [comment]
Approved based on @esune ’s comments.  I’ll leave it to @jleach  to decide to change anything based on the comments or to just merge this.

**Comment by jleach** [comment]
> * should the `dist` folder gitignored?

I think so.

> * any specific reason to use `gulp` vs `tsc` to compile to `js` code?

Gulp calls `tsc` and just runs some other tasks like making the /dist folder.

> * any advantage of using `yarn` over plain-old `npm`?

Its a convention in AFJ and Bifold. Just keeping things the same across all TS projects.

**Comment by jleach** [comment]
@swcurran Needs approval again. I made a few changes to make AFJ work in the .devcontainer, added node support so you can build in the devcontainer, and excluded `/dist` from the repo as per @esune feedback above.

**Review by swcurran — APPROVED** [review]

**Pull request merged**
