### PR TITLE
Shore up the project so it works out of the box (batteries included)

### LINKED ISSUE #29: Does not work as a mediator because of routing issues
As far as I can tell the current repo, as it is, wont work for any wallet because its missing either the ACA-py plugin from the toolbox (which Indecio uses in their running example) or a reverse proxy like  [Caddy](https://caddyserver.com/) to route both `wss://` and `https://` to the same port on the mediator. This means the docker stack will start but I don't think any wallet can meaningfully use it when running. Tested agains [Aries Bifold](https://github.com/hyperledger/aries-mobile-agent-react-native).

For context, the [Aries Bifold](https://github.com/hyperledger/aries-mobile-agent-react-native) wallet uses `https://` to respond to a connection invitation. Then it will open a DIDComm channel via `wss://` for subsequent messaging. The wallet cannot establish the `wss://` connection because `ngrok` is only forwarding `https://` back to the mediator container and, AFAIK, it can not be configured to do two ports simultaneously.

### LINKED ISSUE #30: Documentation points to the wrong org for running
The README points to the `ianco` org for cloning and running when I think it is meant to point to the `hyperledger` org.

### PR DESCRIPTION
**Pull request by jleach**
Being somewhat nube to running a mediator I struggled quite a bit getting this one working as is because of #29. Out of this came some reworking of the project to make it ***just work*** for developers with `docker compose up`. This PR makes it run in a way suitable for most development or demo purposes and it can easily be adapted to run on k8s or OpenShift. The documentation changes I've made comment on how to make it even better for longer lasting tunnels from `ngrok` and wallet persistence. 

- Updated the docs to explain what the components are and why they're started;
- Use docker health checks to determine start conditions for dependencies;
- Only run as a docker stack; not really meant to run containers independently. This removed the need for the `manage` script (for better I hope);
- Removed wait-for-it subdue because startup conditions take care of this;
- Removed reference to tunnelling and nginx from the docker-compose file;
- Fixed #29;
- Fixed #30.

### CODE REVIEW

**Comment by dbluhm** [comment]
There's some really good stuff here. I'd never heard of the healthcheck before, I'll have to start using that :smile: I'm attempting to run this locally, is an ngrok authtoken required? I keep on hitting an ngrok unhealthy failure.

**Comment by jleach** [comment]
Should work without a token but I’ll double check. Works locally for me but I’ll do a fresh clone and test again.

J.

**Comment by jleach** [comment]
@dbluhm Confirmed it runs with and without a ngrok token. I've asked a few more team members to test it to see where the problem is.

**Comment by jleach** [comment]
@dbluhm While it works every time for me another team member commented on a different startup issue. My though is different machines may get the stack into the "ready" state at different times. I'll monitor and do another PR when based on user feedback.

**Comment by jleach** [comment]
@dbluhm Can you try again? This works for several people I know who have tried it (asking for more). Since you last tried I have reduced and fixed the dependencies. As far as I can tell the current repo, as it is, wont work for any wallet because its missing either the ACA-py plugin (which Indecio uses in their running example) or Caddy (which I use) to route both `wss://` and `https://` to the same port. This means the docker stack will start but no wallet can use it.

**Review by dbluhm — APPROVED** [review]
Thanks again for your work here. I discovered what must have been the problem on my end: I'm on fedora and the volumes required `:z` for SELinux context mapping in the container. It was showing up as `service unhealthy` errors. Adding that in and loading an env file, everything started up smoothly. Would be nice to add the `:z` to the volumes (this won't negatively affect other operating systems) but I won't hold this PR up any longer just for that. Thanks!

**Pull request merged**
